# docker logs discord-hltv-matches
# docker logs -f discord-hltv-matches
services:
  bot:
    container_name: bot-hltv
    build:
      context: .
      dockerfile: Dockerfile
    image: lorthe/discord-hltv-matches:latest
    env_file:
      - .env
